name: Run App and Email Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-and-email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python main.py &

      # Step 5: Wait for the screenshot to be generated
      - name: Wait for the app to run
        run: sleep 40 # Wait for the app to launch

      # Step 6: Get the current time for the email subject
      - name: Get current time
        id: get_time
        run: echo "CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      # Step 7: Send an email 
      - name: Send email with screenshot
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Student Management System is running successfully at ${{ env.CURRENT_TIME }}"
          body: |
            Hello ${{ secrets.FULL_NAME }},
            The app has been run successfully.
            No errors found!!
            ${{ secrets.GENERIC }}
            
            Hello ${{ secrets.NAME_2 }},
            The app has been run successfully.
            No errors found!!
            ${{ secrets.GENERIC }}
            
            Hello ${{ secrets.NAME_3 }},
            The app has been run successfully.
            No errors found!!
            ${{ secrets.GENERIC }}
          to: ${{ secrets.PERSONAL_EMAIL_1 }}, ${{ secrets.PERSONAL_EMAIL_2 }}, ${{ secrets.PERSONAL_EMAIL_3 }}
          from: ${{ secrets.EMAIL_USERNAME }}
