name: Run App and Email Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-and-email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python main.py &
        # Run in background so the screenshot can be captured

      # Step 5: Wait for the screenshot to be generated
      - name: Wait for screenshot
        run: sleep 10 # Wait for the app to launch and screenshot to be captured

      # Step 6: Send an email with the screenshot
      - name: Send email with screenshot
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Student Management System is running successfully"
          body: |
            Hello ${{ secrets.FULL_NAME }}
            The app has been run successfully. Screenshot attached for verification.
          to: ${{ secrets.PERSONAL_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: screenshot.png
